### ISSUE TITLE
Compress raise error after disabled

### ISSUE THREAD

**Issue by creadone** [mamantoha/cache#21]
Hi, Anton!

Maybe I didn't understand something but compress option raise error after compress disabled. 

```Crystal
require "cache"

INSTANCE = Cache::MemoryStore(String, Hash(String, String)).new(expires_in: 30.seconds, compress: false)

data = {
  "a" => 1,
  "b" => "bla"
}

result = INSTANCE.fetch("data_key") do
  data
end

pp result
```

```Crystal
In lib/cache/src/cache/stores/memory_store.cr:35:33

 35 | Cache::DataCompressor.inflate(entry.value)
                            ^------
Error: no overload matches 'Cache::DataCompressor.inflate' with type Hash(String, String)

Overloads are:
 - Cache::DataCompressor#inflate(data : String)
```

**Comment by mamantoha** [comment]
Hi @creadone . Thanks for reporting.
Actually I've never used `MemoryStore` for something else than `MemoryStore(String, String)`

**Comment by creadone** [comment]
Thanks!

Ok, no problem. In my project I have 2-level cache before API: API <- Tarantool <- In-memory.  Tarantool protocol based on MessagePack and in app I work with native Crystal hash unpacked by Tarantool driver.

**Comment by mamantoha** [comment]
I forgot to mention this is fixed. You can use `Cache::MemoryStore` for *any*(probably) Crystal object. But `compression` option only suitable for `Cache::MemoryStore(String, String)`.

**Comment by creadone** [comment]
Yes, I checked, it works fine. Note above just for explain case.
